### ISSUE TITLE
Eradicate all Console Logs modifies node_modules in Windows

### ISSUE THREAD

**Issue by vishnuvardhan-s** [Snowcart/kill-console-log#1]
### Issue
Directory path is tested for `node_modules` with slashes
```typescript
  if (dirPath.includes('/node_modules/')) {
```
In Windows, the path looks something like this, so the test fails
```bash
"c:\\Users\\<User>\\test\\node_modules\\js-tokens"
```
### Fix
Test only for `node_modules` string without slashes

**Comment by Snowcart** [comment]
Thanks for this!
